spring:
  datasource:
    url: jdbc:h2:mem:withdraw-service;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: h2
    password: password
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: update  # Use 'update' for auto schema management, or 'create' to recreate schema each time
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true

  flyway:
    enabled: true
    locations: classpath:db/migration

  h2:
    console:
      enabled: true
      path: /h2-console