CREATE TABLE IF NOT EXISTS users
(
    id                    BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name            VARCHAR(255),
    max_withdrawal_amount DECIMAL(18, 2),
    created_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at            TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payment_methods
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id BIGINT       NOT NULL,
    name    VARCHAR(255) NOT NULL UNIQUE,
    CONSTRAINT fk_user FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE
);

CREATE INDEX IF NOT EXISTS idx_payment_methods_name ON payment_methods (name);

-- Insert dummy data
INSERT INTO users (first_name, max_withdrawal_amount)
VALUES ('John Doe', 5000.00),
       ('Jane Smith', 10000.50),
       ('Alice Johnson', 7500.75),
       ('Bob Brown', 12000.25),
       ('Charlie Black', 2500.00);

INSERT INTO payment_methods (user_id, name)
VALUES (1, 'Credit Card'),
       (1, 'PayPal'),
       (2, 'Bank Transfer'),
       (3, 'Bitcoin'),
       (4, 'Stripe'),
       (5, 'Apple Pay');